model:
    arch: unet
data:
    dataset: pascal
    train_split: train
    val_split: val
    img_rows: 512
    img_cols: 512
    #D:\New Student\Data Mining\Project\VOCtrainval_11-May-2012\VOC2012
    #path: /private/home/meetshah/datasets/VOC/060817/VOCdevkit/VOC2012/
    path: D:/New Student/Data Mining/Project/VOCtrainval_11-May-2012/VOC2012/
#    sbd_path: D:/New Student/Data Mining/Project/benchmark/benchmark_RELEASE/
training:
    n_workers: 8
    train_iters: 100000
    batch_size: 8
    val_interval: 1000
    print_interval: 50
    optimizer:
#        name: 'rmsprop'
        name: 'sgd'
        lr: 1.0e-3
        weight_decay: 0.0005
        momentum: 0.99
    loss:
        name: 'cross_entropy'
        size_average: True
    # Augmentations Configuration
    augmentations:
        gamma: 0.2                                     #[gamma varied in 1 to 1+x]
    lr_schedule:
        name: 'poly_lr'
        max_iter: 100
#        name: 'cosine_annealing'
#        T_max: 100

#         name: 'exp_lr'
#         gamma: 0.96
    resume: unet_pascal_best_model.pkl
