model:
    arch: unet
data:
    dataset: pascal
    train_split: train
    val_split: val
    img_rows: 512
    img_cols: 512
    #D:\New Student\Data Mining\Project\VOCtrainval_11-May-2012\VOC2012
    #path: /private/home/meetshah/datasets/VOC/060817/VOCdevkit/VOC2012/
    path: D:/New Student/Data Mining/Project/VOCtrainval_11-May-2012/VOC2012/
#    sbd_path: D:/New Student/Data Mining/Project/benchmark/benchmark_RELEASE/
training:
    n_workers: 8
    train_iters: 30000
    batch_size: 1
    val_interval: 100
    print_interval: 50
    optimizer:
        name: 'sgd'
        lr: 1.0e-3
        weight_decay: 0.0005
        momentum: 0.99
    loss:
        name: 'cross_entropy'
        size_average: False
    lr_schedule:
    resume: unet_pascal_best_model.pkl
